# Generated by Django 3.0.5 on 2020-11-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0003_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
