# Generated by Django 3.0.5 on 2020-11-23 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doubts', '0005_auto_20201123_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='student_name',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
