# Generated by Django 3.0.5 on 2020-11-23 06:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0006_auto_20201123_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='coursename',
            field=models.CharField(blank=True, default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='doubt',
            field=ckeditor.fields.RichTextField(blank=True, default=True),
        ),
    ]
